### PR TITLE
Support Jekyll 3.

### PR DESCRIPTION
**Pull request by ctwise**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Excellent!

Could you make one change? Could you add a comment in the code as to which check corresponds to which version of Jekyll so the code is self documenting? Thanks!

**Comment by ctwise** [comment]
Updated.

**Comment by mojavelinux** [comment]
Thanks @ctwise. Except, a line comment in Ruby uses `#` not `//`. Could you update one more time?

Once that's ready, I think this looks good @paulrayner.

**Comment by ctwise** [comment]
Crap. That's what I get for switching languages every 5 seconds. Sorry, updated.

**Comment by mojavelinux** [comment]
Thanks again for this fix @ctwise!

**Comment by paulrayner** [comment]
Yes! +1. Thanks so much @ctwise.



Paul

**Pull request merged**
