### PR TITLE
resolves #60 don't crash when no page- attributes are defined

### LINKED ISSUE #60: Page with no 'asciidoc_page_attribute_prefix' attributes in header fails to be processed
Noticed this today when writing a new page in `1.1.1`

```
---
---

= Title
my content

```

Fails to be processed with:

```
jekyll-asciidoc-1.1.1/lib/jekyll-asciidoc.rb:109:in `block in generate': undefined method `empty?' for false:FalseClass (NoMethodError)
        from /Users/mkobit/.gem/ruby/2.3.0/gems/jekyll-asciidoc-1.1.1/lib/jekyll-asciidoc.rb:99:in `each'
        from /Users/mkobit/.gem/ruby/2.3.0/gems/jekyll-asciidoc-1.1.1/lib/jekyll-asciidoc.rb:99:in `generate'
```

Which is not very helpful. If the document has an attribute with the prefix (like `page-`):

```
---
---
:page-pizza-topping: pepperoni

= Title
my content 
```

The Jekyll processing seems to work fine (at least with my current `_config.yml`)

It looks to me like the `SafeYAML.load` returns `false` (`FalseClass`) if there is nothing there to load, and then a `Hash` if it is available. This is based on my "debugging" attempt.

Based on my limited research and knowledge, [this StackOverflow answer](http://stackoverflow.com/a/888877/627727) makes it seem that using `.blank?` instead of `.empty?` could fix this, but that seems to only be available in Rails. I'm not sure if hashes are considered "truthy"  or how to treat this. Whatever the idiomatic way is in Ruby, I'd love to do it!

### PR DESCRIPTION
**Pull request by mojavelinux**

### CODE REVIEW

**Comment by paly2** [comment]
I have the same problem ([#60](https://github.com/asciidoctor/jekyll-asciidoc/issues/60)), please merge this pull request !

**Comment by mojavelinux** [comment]
@mkobit Can you confirm the fix? Once we merge, would you be able to make a 1.1.2 release?

**Comment by paly2** [comment]
The fix works, I tested it

**Comment by mojavelinux** [comment]
Oh, super!

**Comment by mojavelinux** [comment]
Thanks!

**Pull request merged**
